local Scan = WowVision.minimapScan

-- Gathering node names as the minimap names them, per tracking spell and
-- client locale (Vanilla to Wrath). Taken from Sku 43.9
-- (SkuCore/minimapScanner.lua, RessourceTypes and its French names).
-- The scan matches by containment, so variants such as "Verkümmertes
-- Silberblatt" still count as Silberblatt. A locale missing here falls
-- back to enUS.
Scan.gatheringNames = {
    herbs = {
        spells = { 2383 }, -- Find Herbs
        enUS = {
            "Peacebloom",
            "Silverleaf",
            "Earthroot",
            "Mageroyal",
            "Briarthorn",
            "Stranglekelp",
            "Bruiseweed",
            "Wild Steelbloom",
            "Grave Moss",
            "Kingsblood",
            "Liferoot",
            "Fadeleaf",
            "Goldthorn",
            "Khadgar's Whisker",
            "Wintersbite",
            "Firebloom",
            "Purple Lotus",
            "Arthas' Tears",
            "Sungrass",
            "Blindweed",
            "Ghost Mushroom",
            "Gromsblood",
            "Golden Sansam",
            "Dreamfoil",
            "Mountain Silversage",
            "Plaguebloom",
            "Icecap",
            "Black Lotus",
            "Felweed",
            "Dreaming Glory",
            "Terocone",
            "Ragveil",
            "Ancient Lichen",
            "Netherbloom",
            "Nightmare Vine",
            "Mana Thistle",
            "Fel Lotus",
            "Goldclover",
            "Tiger Lily",
            "Adder's Tongue",
            "Talandra's Rose",
            "Lichbloom",
            "Icethorn",
            "Frost Lotus",
            "Bloodthistle",
        },
        deDE = {
            "Friedensblume",
            "Silberblatt",
            "Erdwurzel",
            "Maguskönigskraut",
            "Wilddornrose",
            "Würgetang",
            "Beulengras",
            "Wildstahlblume",
            "Grabmoos",
            "Königsblut",
            "Lebenswurz",
            "Blassblatt",
            "Golddorn",
            "Khadgars Schnurrbart",
            "Winterbiss",
            "Feuerblüte",
            "Lila Lotus",
            "Arthas' Tränen",
            "Sonnengras",
            "Blindkraut",
            "Geisterpilz",
            "Gromsblut",
            "Goldener Sansam",
            "Traumblatt",
            "Bergsilbersalbei",
            "Pestblüte",
            "Eiskappe",
            "Schwarzer Lotus",
            "Teufelsgras",
            "Traumwinde",
            "Terozapfen",
            "Zottelkappe",
            "Urflechte",
            "Netherblüte",
            "Alptraumranke",
            "Manadistel",
            "Teufelslotus",
            "Goldklee",
            "Tigerlilie",
            "Schlangenzunge",
            "Talandras Rose",
            "Lichblüte",
            "Eisdorn",
            "Frostlotus",
            "Blutdistel",
        },
        frFR = {
            "Pacifique",
            "Feuillargent",
            "Terrestrine",
            "Mage royal",
            "Eglantine",
            "Etouffante",
            "Doulourante",
            "Aciérite sauvage",
            "Tombeline",
            "Sang-royal",
            "Vietérule",
            "Pâlerette",
            "Dorépine",
            "Moustache de Khadgar",
            "Hivernale",
            "Fleur de feu",
            "Lotus pourpre",
            "Larmes d'Arthas",
            "Soleillette",
            "Aveuglette",
            "Champignon fantôme",
            "Gromsang",
            "Sansam doré",
            "Feuillerêve",
            "Sauge-argent des montagnes",
            "Fleur de peste",
            "Calot de glace",
            "Lotus noir",
            "Gangrelette",
            "Glaurier",
            "Terocône",
            "Voile-misère",
            "Lichen ancien",
            "Néantine",
            "Cauchemardelle",
            "Chardon de mana",
            "Gangrelotus",
            "Trèfle doré",
            "Lys tigré",
            "Langue de serpent",
            "Rose de Talandra",
            "Fleur-de-liche",
            "Glacépine",
            "Lotus givré",
            "Chardon sanglant",
        },
    },
    mining = {
        spells = { 2580 }, -- Find Minerals
        enUS = {
            "Copper Vein",
            "Tin Vein",
            "Silver Vein",
            "Ooze Covered Silver Vein",
            "Iron Deposit",
            "Gold Vein",
            "Ooze Covered Gold Vein",
            "Mithril Deposit",
            "Ooze Covered Mithril Deposit",
            "Truesilver Deposit",
            "Ooze Covered Truesilver Deposit",
            "Small Thorium Vein",
            "Ooze Covered Thorium Vein",
            "Rich Thorium Vein",
            "Ooze Covered Rich Thorium Vein",
            "Dark Iron Deposit",
            "Fel Iron Deposit",
            "Adamantite Deposit",
            "Rich Adamantite Deposit",
            "Khorium Vein",
            "Cobalt Deposit",
            "Rich Cobalt Deposit",
            "Saronite Deposit",
            "Rich Saronite Deposit",
            "Pure Saronite Deposit",
            "Titanium Vein",
            "Pure Adamantite Deposit",
        },
        deDE = {
            "Kupfervorkommen",
            "Zinnvorkommen",
            "Silbervorkommen",
            "Brühschlammbedecktes Silbervorkommen",
            "Eisenvorkommen",
            "Goldvorkommen",
            "Brühschlammbedecktes Goldvorkommen",
            "Mithrilablagerung",
            "Brühschlammbedeckte Mithrilablagerung",
            "Echtsilberablagerung",
            "Brühschlammbedeckte Echtsilberablagerung",
            "Kleines Thoriumvorkommen",
            "Brühschlammbedecktes Thoriumvorkommen",
            "Reiches Thoriumvorkommen",
            "Brühschlammbedecktes reiches Thoriumvorkommen",
            "Dunkeleisenablagerung",
            "Teufelseisenvorkommen",
            "Adamantitablagerung",
            "Reiche Adamantitablagerung",
            "Khoriumvorkommen",
            "Kobaltablagerung",
            "Reiche Kobaltablagerung",
            "Saronitablagerung",
            "Reiche Saronitablagerung",
            "Reine Saronitablagerung",
            "Titanvorkommen",
            "Reine Adamantitablagerung",
        },
        frFR = {
            "Filon de cuivre",
            "Filon d'étain",
            "Filon d'argent",
            "Filon d'argent couvert de limon",
            "Gisement de fer",
            "Filon d'or",
            "Filon d'or couvert de limon",
            "Gisement de mithril",
            "Gisement de mithril couvert de vase",
            "Gisement de vrai-argent",
            "Gisement de vrai-argent couvert de vase",
            "Petit filon de thorium",
            "Filon de thorium couvert de limon",
            "Riche filon de thorium",
            "Riche filon de thorium couvert de limon",
            "Gisement de sombrefer",
            "Gisement de gangrefer",
            "Gisement d'adamantite",
            "Riche gisement d'adamantite",
            "Filon de khorium",
            "Gisement de cobalt",
            "Riche gisement de cobalt",
            "Gisement de saronite",
            "Riche gisement de saronite",
            "Gisement de saronite pure",
            "Veine de titane",
            "Gisement d'adamantite pure",
        },
    },
    chests = {
        spells = { 2481 }, -- Find Treasure
        enUS = {
            "Damaged Chest",
            "Dented Chest",
            "Large Battered Chest",
            "Large Iron Bound Chest",
            "Large Mithril Bound Chest",
            "Large Solid Chest",
            "Locked Chest",
            "Primitive Chest",
            "Rusty Chest",
            "Solid Chest",
            "Sunken Chest",
            "Tattered Chest",
            "Worn Chest",
            "Adamantite Bound Chest",
            "Fel Iron Chest",
        },
        deDE = {
            "Beschädigte Truhe",
            "Verbeulte Truhe",
            "Große ramponierte Truhe",
            "Große eisenbeschlagene Truhe",
            "Große mithrilbeschlagene Truhe",
            "Große robuste Truhe",
            "Verschlossene Truhe",
            "Primitive Truhe",
            "Rostige Truhe",
            "Robuste Truhe",
            "Versunkene Truhe",
            "Ramponierte Truhe",
            "Abgenutzte Truhe",
            "Adamantitbeschlagene Truhe",
            "Teufelseisentruhe",
        },
        frFR = {
            "Coffre endommagé",
            "Coffre abîmé",
            "Grand coffre endommagé",
            "Grand coffre cerclé de fer",
            "Grand coffre cerclé de mithril",
            "Grand coffre solide",
            "Coffre verrouillé",
            "Coffre primitif",
            "Coffre rouillé",
            "Coffre solide",
            "Coffre englouti",
            "Coffre en morceaux",
            "Coffre usé",
            "Coffre cerclé d'adamantite",
            "Coffre en gangrefer",
        },
    },
}
